src/objects/Page__c.object
<CustomObject>
    <fields>
        <fullName>Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Template</label>
        <referenceTo>Template_Page__c</referenceTo>
        <relationshipLabel>Pages</relationshipLabel>
        <relationshipName>Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Page_Content__c.object
<CustomObject><fields>
        <fullName>Row__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>A Row is a horizontal segment of a web page, which has a Style applied to it. Content is displayed inside of a row.</inlineHelpText>
        <label>Row Name</label>
        <referenceTo>Row__c</referenceTo>
        <relationshipName>Page_Content</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Junction object between Content, Pages, and Rows.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Element</label><nameField>
        <displayFormat>E {0}</displayFormat>
        <label>Element Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Elements</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

src/objects/Row__c.object
<CustomObject><fields>
        <fullName>Row__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Row</label>
        <referenceTo>Template_Row__c</referenceTo>
        <relationshipName>Rows</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Row</label><nameField>
        <label>Row Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Rows</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/objects/Template_Page__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Page Template</label><nameField>
        <label>_Page Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Page Templates</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

src/objects/Template_Page_Content__c.object
<CustomObject><fields>
        <fullName>Row__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Row</label>
        <referenceTo>Template_Row__c</referenceTo>
        <relationshipName>Template_Containers</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Row Elements of Page Templates</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>false</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Element</label><nameField>
        <label>Element</label>
        <type>Text</type>
    </nameField><pluralLabel>Elements</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel><startsWith>Vowel</startsWith></CustomObject>

src/objects/Template_Row__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Row</label><nameField>
        <label>Row</label>
        <type>Text</type>
    </nameField><pluralLabel>Rows</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

src/classes/PageBuilder_ControllerTest.cls
@isTest
private class PageBuilder_ControllerTest {
    @isTest static void test_method_one() { 
        Integer templateSetSize = 1;
        PageReference pageRef;

        Template_Page__c tp = [SELECT Id, Name FROM Template_Page__c];
        PageBuilder_Controller pbController = new PageBuilder_Controller();
        system.assertEquals(pbController.templateMap, null);
        
        pbController.getTemplates(); 
        //validate the gettemplates queried the set
        system.assertEquals(pbController.templateMap.size(), templateSetSize);
        
        //validate that without the template ID, the method returns null
        pageRef = Page.PageBuilder;
        test.setCurrentPage(pageRef);
        system.assertEquals(pbController.buildPage(), null);


        //validate without the PageName, it errors our
        pageRef = Page.PageBuilder;
        test.setCurrentPage(pageRef);
        pageRef.getParameters().put('template', tp.id);
        pbController.buildPage();
        system.assert(TestUtils.messageFound(ApexPages.Severity.ERROR, 'Please provide a valid Name for your page.'));

        //validate that the with the PageName and Template populated, a page is created.
        pageRef = Page.PageBuilder;
        test.setCurrentPage(pageRef);
        pageRef.getParameters().put('template', tp.id);
        pbController.PageName = 'My Test Page';
        pbController.buildPage();

        tp = [SELECT Id, Name, (SELECT Id FROM Pages__r) FROM Template_Page__c];
        system.assert(tp.Pages__r.size() == templateSetSize);

        //validate the row was created
        List<Row__c> rList = [SELECT Id FROM Row__c];
        system.assertEquals(rList.size(), templateSetSize);

        //validate the page content was created
        List<Page_Content__c> pcList = [SELECT Id FROM Page_Content__c];
        system.assertEquals(pcList.size(), templateSetSize);
    }



    @TestSetup 
    public static void createData() {
        Template_Page__c tp = TestUtils.createTemplatePage(true);
        Template_Row__c tr = TestUtils.createTemplateRow(true, tp);
        Template_Page_Content__c tpc = TestUtils.createTemplatePageContent(true, tp, tr);
    }
}