src/objects/Payment__c.object
<CustomObject>
    <description>Details of payments made through pay.gov</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pay_Gov_Tracking_Id__c</fullName>
        <description>The tracking Id returned by pay.gov</description>
        <label>Pay Gov Tracking ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The transaction amount</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>The DateTime of the payment transaction, as returned from pay.gov</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The payment transaction status, as returned by pay.gov</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>SP{000000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Refund__c.object
<CustomObject>
    <description>A detail object for a Payment master object.  The refund of a payment in pay.gov.</description>
    <fields>
        <fullName>Pay_Gov_Tracking_Id__c</fullName>
        <description>The id returned from pay.gov</description>
        <label>Pay Gov Tracking ID</label>
        <length>21</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <description>The M/D lookup that ties a refund to a payment.</description>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Refunds</relationshipLabel>
        <relationshipName>Refunds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <description>The amount of the refund</description>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <description>The date/time of the refund, as returned by pay.gov</description>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Status__c</fullName>
        <description>The refund status, as returned by pay.gov</description>
        <label>Transaction Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Refund</label>
    <nameField>
        <displayFormat>SR{000000000}</displayFormat>
        <label>Refund ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MyOrdersComponentControllerTest.cls
/*
Name: MyOrdersComponentControllerTest
Author: Dan Kelner
Date Created: 10/03/16
Purpose: Test class for MyOrdersComponentController
*/
@isTest(SeeAllData = true)
public class MyOrdersComponentControllerTest {
    
    public static testMethod void runTest(){
        //Create basic test data
        Test.startTest();
        Account myAccount = new Account(Name = 'Testing');
        insert myAccount;
        
        Product2[] prod = [SELECT Name FROM Product2 LIMIT 1];
        Pricebook2 pbook = [SELECT ID FROM Pricebook2 WHERE IsStandard = true LIMIT 1];
        
        Order myOrder = new Order(AccountID = myAccount.ID, EffectiveDate = Date.today().addDays(-2), Status = 'Draft', Pricebook2ID = pbook.ID);
        insert myOrder;
        
        PricebookEntry pbe = [SELECT ID FROM PricebookEntry WHERE Pricebook2ID = :pbook.ID AND Product2ID = :prod[0].ID AND IsActive = true LIMIT 1];
        
        OrderItem myOrderItem = new OrderItem(OrderID = myOrder.ID, PricebookEntryID = pbe.ID, Quantity = 1, ServiceDate = myOrder.EffectiveDate, UnitPrice = 1000);
        insert myOrderItem;
        
        Payment__c paymentObj = new Payment__c(Order__c = myOrder.ID, Transaction_Date__c = System.now().addDays(-2), Transaction_Amount__c = 500, Transaction_Status__c = 'Success');
        insert paymentObj;
        
        Refund__c refundObj = new Refund__c(Payment__c = paymentObj.ID, Transaction_Date__c = System.now(), Transaction_Amount__c = 250, Transaction_Status__c = 'Success');
        insert refundObj;
        
        Test.stopTest();
        
        //Run through controller methods and achieve code coverage
        MyOrdersComponentController ctrl = new MyOrdersComponentController();
        System.assertEquals('January', ctrl.getMonth(1));
        ctrl.orders = [SELECT EffectiveDate, OrderNumber, AccountID, 
                           (SELECT OrderID, Pricebookentry.Product2.Name FROM OrderItems),
                           (SELECT Order__c, Transaction_Date__c, Pay_Gov_Tracking_Id__c, Transaction_Amount__c, Transaction_Status__c FROM Payments__r)
                       FROM Order WHERE ID = :myOrder.ID];
        System.debug('Order Map size: ' + ctrl.getOrderMap().size());
    }
}